# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-29 23:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prospects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('feel', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('budget', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
