# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-29 23:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('enquiry', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
